import type { Metadata } from "next"
import { Host_Grotesk } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Crud Todo App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${hostGrotesk.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}